# plex/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: sonarr

configMapGenerator:
  - name: sonarr-env
    namespace: sonarr
    literals:
      - TZ="Europe/Budapest",
      - PUID="0",
      - PGID="0"
resources:
  - svc.yaml
  - ns.yaml
  - deployment.yaml
  - ingress.yaml