# plex/deployment.yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: tdarr-node
  namespace: tdarr-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tdarr-node
  template:
    spec:
      containers:
        - name: tdarr-node
          image: haveagitgat/tdarr_node:2.25.01
          resources:
            requests:
              gpu.intel.com/i915: 1
            limits:
              gpu.intel.com/i915: 1
          envFrom:
            - configMapRef:
                name: tdarr-node-env
          volumeMounts:
            - name: videos
              mountPath: /media/movies
          securityContext:
            privileged: true
            capabilities:
              drop: ["ALL"]              
      volumes:
        - name: videos
          nfs:
            server: 192.168.50.40
            path: /volume1/homes/jolcsak/Private/sss


