# plex/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: tdarr-node

configMapGenerator:
  - name: tdarr-node-env
    namespace: tdarr-node
    literals:
      - TZ="Europe/Budapest",
      - PUID="0",
      - PGID="0"
      - serverIP="192.168.50.43"
      - transcodegpuWorkers="1"
      - healthcheckcpuWorkers="2"
resources:
  - ns.yaml
  - deployment.yaml