# plex/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: grafana

configMapGenerator:
  - name: grafana-env
    namespace: grafana
    literals:
      - TZ="Europe/Budapest",
      - PUID="0",
      - PGID="0"
resources:
  - svc.yaml
  - ns.yaml
  - deployment.yaml
  - ingress.yaml