# plex/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: homepage

configMapGenerator:
  - name: homepage-env
    namespace: homepage
    literals:
      - TZ="Europe/Budapest"
resources:
  - svc.yaml
  - ns.yaml
  - deployment.yaml
  - ingress.yaml