# plex/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: tdarr

configMapGenerator:
  - name: tdarr-env
    namespace: tdarr
    literals:
      - TZ="Europe/Budapest",
      - PUID="0",
      - PGID="0"
      - internalNode="false"
resources:
  - ns.yaml
  - svc.yaml
  - secret.yaml
  - deployment.yaml
  - ingress.yaml